### ISSUE TITLE
Geographical instance support

### ISSUE THREAD

**Issue by secrutiny-jwinchester** [chronicle/api-samples-python#70]
For Europe tenants
CHRONICLE_API_BASE_URL = "https://backstory.googleapis.com"
needs to be replaced with
CHRONICLE_API_BASE_URL = "https://europe-backstory.googleapis.com"
Please can I make a suggestion that this is fully supported with he option of a region argument on the commandline?

For example
python3 -m detect.v2.list_rules -c ./credential.json -r europe

Where r is the region?

**Comment by secrutiny-jwinchester** [comment]
Thanks Daniel, that's good to know - I didn't check the Pull Requests before logging the issue :-/ apologies.

**Comment by daabr** [comment]
Serendipitous timing :)

**Comment by daabr** [comment]
FYI, PR #71  integrates the new region flag into all the existing samples.
